export interface Project {
  id: string;
  name: string;
  type: string;
  size: string;
  url: string;
  logo: string;
  image: string | null;
  description: string;
  technologies: string[];
  details: string[];
}

export const projects: Project[] = [
   {
    id: "1",
    name: "Log Automobile",
    type: "Full Stack",
    size: "650 MB",
    url: "https://lamborghini-group.ch/en",
    logo: "/logo.svg",
    image: "/project-image-1.png",
    description: "Full-stack automobile club management platform",
    technologies: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "Firebase",
      "Redux Toolkit",
      "React Query",
      "Framer Motion",
      "Sentry",
      "Node.js",
      "next-intl",
    ],
    details: [
      "Full-stack web app for managing an automobile club — members, events, forums, garage, news, and a member directory with chat.",
      "Built on Next.js 15 App Router with Firebase as the backend (Firestore, Auth, Storage, Cloud Functions).",
      "Internationalized with next-intl (EN/DE), state managed via Redux Toolkit + React Query, UI built with Radix UI + shadcn/c components.",
      "Cloud Functions handle email notifications, event reminders, and user status triggers via scheduled jobs.",
      "Deployed on Firebase App Hosting (Cloud Run), with Sentry for error monitoring across client, server, and edge.",
    ],
  },
  {
    id: "2",
    name: "Verified Offers",
    type: "Full Stack",
    size: "820 MB",
    url: "https://verified-offers-b0e04.web.app",
    logo: "/verified-logo.png",
    image: "/project-image-3.png",
    description: "Full-stack real estate offer management platform",
    technologies: [
      "React 18",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "Firebase",
      "Redux Toolkit",
      "React Query",
      "React Hook Form",
      "Recharts",
      "Stripe",
      "Zod",
      "shadcn/ui",
      "Radix UI",
      "jsPDF",
      "Lucide React",
    ],
    details: [
      "Full-stack web app for managing real estate offers end-to-end — buyers submit offers, sellers counter or accept, with full negotiation history, document management, and investment analysis tools.",
      "Built with React 18 + Vite on the frontend, Firebase as the backend (Firestore, Auth, Storage, Cloud Functions) for real-time offer tracking and notifications.",
      "Role-based access for buyers, sellers, and listing agents with verified buyer badges, offer expiry logic, SMS/email notifications, and shareable seller links.",
      "Features an Investment Analyzer with Flip, Rental, BRRRR, and Exit strategy tabs, PDF export via jsPDF, and Stripe-powered subscription tiers for pro features.",
      "Deployed on Firebase Hosting with real-time Firestore listeners, counter offer workflows, document uploads, and activity timelines per offer.",
    ],
  },
  {
    id: "3",
    name: "Amora",
    type: "Full Stack",
    size: "1.2 GB",
    url: "https://amora-tawny.vercel.app",
    logo: "/amora.png",
    image: "/project-image-4.png",
    description: "Full-stack Transportation Management System (TMS) for freight dispatching operations",
    technologies: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "PostgreSQL",
      "Prisma ORM",
      "Redux Toolkit",
      "Firebase Storage",
      "JWT",
      "Nodemailer",
      "Recharts",
      "Zod",
      "Formik",
      "Framer Motion",
    ],
    details: [
      "Full-stack TMS web app for managing freight operations — loads, drivers, fleet, customers, documents, and billing across three role-based portals (Admin, Dispatcher, Driver).",
      "Built on Next.js App Router with a PostgreSQL database (Neon) managed via Prisma ORM. Authentication uses JWT with refresh token rotation, bcrypt password hashing, and secure password reset via Nodemailer.",
      "Role-based access control separates Admin, Dispatcher, and Driver workflows. Dispatchers manage the full load lifecycle (Unassigned → Assigned → In Transit → Delivered → Billed → Closed), assign drivers and vehicles, upload billing proofs, and track multi-stop routes.",
      "Drivers get a dedicated portal to accept/reject loads, mark stop arrivals, upload PODs, and report issues. Fleet management covers vehicles, trailers, fuel reports, and maintenance logs.",
      "Driver performance is tracked with detailed post-load ratings (punctuality, communication, cargo handling). Firebase Storage handles document uploads (BOL, POD, invoices). Dashboard analytics powered by Recharts. Audit logging tracks all critical actions across the platform.",
    ],
  },
  {
    id: "4",
    name: "Tribotix",
    type: "Frontend",
    size: "320 MB",
    url: "https://tribotix.netlify.app",
    logo: "/logo1.png",
    image: "/project-image-5.png",
    description: "Agency marketing website for AI-powered digital services",
    technologies: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "Nodemailer",
      "Framer Motion",
      "Lucide React",
      "React Icons",
      "React Toastify",
      "React Intersection Observer",
      "DM Sans",
    ],
    details: [
      "Single-page marketing website for Tribotex — a tech agency offering AI automation, web/mobile development, SaaS solutions, sales & marketing, business automation, and design & branding services.",
      "Built on Next.js App Router with a fully responsive layout using Tailwind CSS and DM Sans typography. Smooth scroll navigation links all sections via anchor IDs with a sticky navbar and mobile hamburger menu.",
      "Hero section features a looping background video at 0.5x playback speed with animated gradient CTA buttons and glow effects. Services section displays a 6-card responsive grid covering SaaS, Web & Mobile, Sales, Automation, AI, and Design.",
      "AI Automation section uses a two-column layout with scroll-triggered Framer Motion animations highlighting custom pipelines, AI chatbots, and sales agents.",
      "Contact form collects lead details (name, email, phone, company, project type, message) and submits to a Next.js API route that sends emails via Gmail SMTP using Nodemailer. Toast notifications handle success/error feedback via React Toastify. Footer includes an animated FAQ accordion with AnimatePresence, service links, quick links, and contact info.",
    ],
  },
  {
    id: "5",
    name: "USPA League",
    type: "Full Stack",
    size: "480 MB",
    url: "https://uspa-league.web.app",
    logo: "/logo.svg",
    image: "/project-image-6.png",
    description: "Sports league platform and marketing demo for competitive league management",
    technologies: [
      "React 17",
      "JavaScript",
      "Create React App",
      "Redux Toolkit",
      "React Router v5",
      "Firebase 8",
      "Socket.IO Client",
      "Reactstrap",
      "Bootstrap",
      "React Toastify",
      "React USA Map",
      "React Datepicker",
      "ApexCharts",
      "Moment",
      "node-sass",
    ],
    details: [
      "Single-page app with public landing pages and authenticated dashboard routes. Landing page built from Header, About, Tournament, and Sponsor sections with a sticky navbar and footer shared across public/auth layouts.",
      "About section explains USPA League's competitive rating system, fair matchups, playoffs, and trophies. Interactive US state market map shows active markets and enables league discovery.",
      "Auth flow with Signup, Signin, and protected dashboard routes. Dashboard includes leagues, standings, matches, schedules, playoffs, performance, chat, rosters, and facility management.",
      "Real-time updates via Socket.IO events for users, match status, and messaging. Toast notifications and loading overlays provide UX feedback throughout the app.",
      "State managed with Redux Toolkit across all dashboard modules. Charts and performance analytics powered by ApexCharts. Date handling via Moment and React Datepicker.",
    ],
  },
  {
    id: "6",
    name: "Sportfolio",
    type: "Frontend",
    size: "210 MB",
    url: "https://sportfolio-frontend.netlify.app",
    logo: "/logo.svg",
    image: "/project-image-7.png",
    description: "Marketing landing site and simulated sports exchange demo — fractional team ownership as a concept, with rich mock market data rendered entirely in the browser.",
    technologies: [
      "React 19",
      "Vite 7",
      "React Router 7",
      "Tailwind CSS 4",
      "@tailwindcss/vite",
      "ESLint 9",
      "JavaScript",
    ],
    details: [
      "Sportfolio presents the concept of fractional sports team ownership framed like equities — combining a bold marketing landing page with a fully simulated trading and research surface, all driven by mock data in the browser.",
      "Home route features a sticky navbar, animated hero with asset visuals, a stats strip with animated headline metrics, and two-column content blocks alternating blue/dark themes across four narrative sections covering tokenization, athlete value, leagues, and ownership.",
      "Demo route (/demo) delivers a full trading-surface feel: live-style market ticker, sortable and searchable team token table with sparklines, athlete intrinsic value cards, time & sales tape, venue depth chart, and an IPO pipeline rail.",
      "Additional demo panels include rotating desk insights and a session clock synced to US Eastern time — all data sourced from src/data/mockData.js with no backend required.",
      "Built with React 19 and Vite 7 for fast dev and build cycles. Tailwind CSS 4 via the official Vite plugin handles all styling. Routing handled by React Router 7 with clean client-side navigation between Home and Demo.",
    ],
  },
];

// Legacy alias kept for any existing imports
export const dummyProjects = projects.map((p) => ({
  id: p.id,
  name: p.name,
  size: p.size,
  type: p.type,
}));

export type ProjectRow = (typeof dummyProjects)[number];
